# The current version of the config schema
version: 1
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". If blank, will refer to environment. Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    pl: pr list --author @me
    pc: pr create
    ps: pr checkout
    po: pr view --web
    show-conflicts: pr-list 'map(select(.mergeable == "CONFLICTING"))' '{{range .}}{{tablerow ((autocolor (colorstate .) (printf "#%v" .number)) | hyperlink .url) (truncate 50 .title) (colorhex "#ffa500" .headRefName) ((timeago .updatedAt) | autocolor "blue")}}{{end}}' -- --author='@me'
    show-reviewable: pr-list 'map(select(.state == "OPEN" and .mergeable != "CONFLICTING" and (.isDraft | not) and (.statusCheckRollup | all(.conclusion != "FAILURE"))))' '{{range .}}{{tablerow (printf "[%s](<%s>)" .title .url)}}{{end}}' -- --author='@me'
    needs-work: pr-list 'map(select(.mergeable == "CONFLICTING" or (.statusCheckRollup | any(.conclusion == "FAILURE"))))' '{{range .}}{{tablerow ((autocolor (colorstate .) (printf "#%v" .number)) | hyperlink .url) (truncate 50 .title) (colorhex "#ffa500" .headRefName) ((timeago .updatedAt) | autocolor "blue")}}{{end}}' -- --author='@me'
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
